(function(){var h={},mt={},c={id:"42a0d9955cd3e78d031be058104d1215",dm:["photoworld.com.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,apps:''};var p=!0,q=null,r=!1;mt.g={};mt.g.ua=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.wa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,b,g){var e;g.D&&(e=new Date,e.setTime(e.getTime()+g.D));document.cookie=a+"="+b+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(e?"; expires="+e.toGMTString():"")+(g.Ka?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.p={};mt.p.Ca=function(a){return document.getElementById(a)};mt.p.ha=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return q};
(mt.p.Ja=function(){function a(){if(!a.t){a.t=p;for(var b=0,m=e.length;b<m;b++)e[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var g=r,e=[],k;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",k,r);a()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),a())});(function(){if(!g)if(g=p,"complete"===document.readyState)a.t=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
k,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",k);window.attachEvent("onload",a);var e=r;try{e=window.frameElement==q}catch(m){}document.documentElement.doScroll&&e&&b()}})();return function(b){a.t?b():e.push(b)}}()).t=r;mt.event={};mt.event.d=function(a,b,g){a.attachEvent?a.attachEvent("on"+b,function(e){g.call(a,e)}):a.addEventListener&&a.addEventListener(b,g,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.n={};mt.n.parse=function(){return(new Function('return (" + source + ")'))()};
mt.n.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var e=g[a];if(e)return e;e=a.charCodeAt();return"\\u00"+Math.floor(e/16).toString(16)+(e%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===q)return"null";if(e instanceof Array){var g=["["],n=e.length,m,f,d;for(f=0;f<n;f++)switch(d=e[f],typeof d){case "undefined":case "function":case "unknown":break;default:m&&g.push(","),g.push(mt.n.stringify(d)),m=1}g.push("]");return g.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+b(e.getMonth()+1)+"-"+b(e.getDate())+"T"+b(e.getHours())+":"+b(e.getMinutes())+":"+b(e.getSeconds())+'"';m=["{"];f=mt.n.stringify;for(n in e)if(Object.prototype.hasOwnProperty.call(e,n))switch(d=
e[n],typeof d){case "undefined":case "unknown":case "function":break;default:g&&m.push(","),g=1,m.push(f(n)+":"+f(d))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.e=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ga=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Ia=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.A=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return r}return p};
mt.localStorage.set=function(a,b,g){var e=new Date;e.setTime(e.getTime()+g||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.A()&&(mt.localStorage.f.expires=e.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,b),mt.localStorage.f.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),g=a.substring(0,b)-0;if(g&&g>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.A())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(e){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.A())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(g){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.L={};mt.L.log=function(a,b){var g=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=g;g.onload=g.onerror=g.onabort=function(){g.onload=g.onerror=g.onabort=q;g=window[e]=q;b&&b(a)};g.src=a};mt.M={};
mt.M.oa=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
mt.M.Ba=function(a,b,g,e,k){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+g+'" height="'+e+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(k||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+g+'" height="'+e+'" src="'+b+'" flashvars="'+(k||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(a,b){var g=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return g?g[3]:q};mt.url.Ea=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.la=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.P=function(a){return(a=mt.url.la(a))?a.replace(/:\d+$/,""):a};mt.url.Da=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.B={Fa:"http://tongji.baidu.com/hm-web/welcome/ico",J:"hm.baidu.com/hm.gif",Y:"baidu.com",ra:"hmmd",sa:"hmpl",qa:"hmkw",pa:"hmci",ta:"hmsr",l:0,i:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",Ha:0,ca:6E5,da:10,N:1024,ba:1,m:2147483647,V:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={j:{},d:function(a,g){this.j[a]=this.j[a]||[];this.j[a].push(g)},q:function(a,g){this.j[a]=this.j[a]||[];for(var e=this.j[a].length,k=0;k<e;k++)this.j[a][k](g)}};return h.r=a})();
(function(){function a(a,e){var k=document.createElement("script");k.charset="utf-8";b.e(e,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=q,e()}:k.onload=function(){e()});k.src=a;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(k,n)}var b=mt.lang;return h.load=a})();
(function(){var a=mt.p,b=mt.event,g=mt.g,e=h.B,k=[],n={W:function(){c.ctrk&&(b.d(document,"mouseup",n.aa()),b.d(window,"unload",function(){n.w()}),setInterval(function(){n.w()},e.ca))},aa:function(){return function(a){a=n.ia(a);if(""!==a){var f=(e.protocol+"//"+e.J+"?"+h.b.U().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;f+(e.m+"").length>e.N||(f+encodeURIComponent(k.join(",")+(k.length?",":"")).length+(e.m+"").length>e.N&&n.w(),k.push(a),(k.length>=e.da||/t:a/.test(a))&&n.w())}}},
ia:function(b){if(0===e.ba){var f=b.target||b.srcElement,d=f.tagName.toLowerCase();if("embed"==d||"object"==d)return""}g.ua?(f=Math.max(document.documentElement.scrollTop,document.body.scrollTop),d=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),d=b.clientX+d,f=b.clientY+f):(d=b.pageX,f=b.pageY);var l=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:d-=l/2;break;case 2:d-=l}d="{x:"+d+",y:"+f+",";f=b.target||b.srcElement;
return d=(b="a"==f.tagName.toLowerCase()?f:a.ha(f))?d+("t:a,u:"+encodeURIComponent(b.href)+"}"):d+"t:b}"},w:function(){0!==k.length&&(h.b.a.et=2,h.b.a.ep="["+k.join(",")+"]",h.b.h(),k=[])}};h.r.d("pv-b",n.W);return n})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.C.ma()+","+h.C.ka();h.b.h()}}function b(){clearTimeout(x);var a;v&&(a="visible"==document[v]);y&&(a=!document[y]);f="undefined"==typeof a?p:a;if((!m||!d)&&f&&l)w=p,s=+new Date;else if(m&&d&&(!f||!l))w=r,t+=+new Date-s;m=f;d=l;x=setTimeout(b,100)}function g(d){var a=document,f="";if(d in a)f=d;else for(var e=["webkit","ms","moz","o"],b=0;b<e.length;b++){var s=e[b]+d.charAt(0).toUpperCase()+d.slice(1);if(s in a){f=
s;break}}return f}function e(d){if(!("focus"==d.type||"blur"==d.type)||!(d.target&&d.target!=window))l="focus"==d.type||"focusin"==d.type?p:r,b()}var k=mt.event,n=h.r,m=p,f=p,d=p,l=p,u=+new Date,s=u,t=0,w=p,v=g("visibilityState"),y=g("hidden"),x;b();(function(){var d=v.replace(/[vV]isibilityState/,"visibilitychange");k.d(document,d,b);k.d(window,"pageshow",b);k.d(window,"pagehide",b);"object"==typeof document.onfocusin?(k.d(document,"focusin",e),k.d(document,"focusout",e)):(k.d(window,"focus",e),
k.d(window,"blur",e))})();h.C={ma:function(){return+new Date-u},ka:function(){return w?+new Date-s+t:t}};n.d("pv-b",function(){k.d(window,"unload",a())});return h.C})();
(function(){function a(d){for(var f in d)if({}.hasOwnProperty.call(d,f)){var b=d[f];e.e(b,"Object")||e.e(b,"Array")?a(b):d[f]=String(b)}}function b(d){return d.replace?d.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):d}var g=mt.L,e=mt.lang,k=mt.n,n=h.B,m=h.r,f={Q:q,o:[],z:0,R:r,init:function(){f.c=0;f.Q={push:function(){f.I.apply(f,arguments)}};m.d("pv-b",function(){f.ea();f.fa()});m.d("pv-d",f.ga);m.d("stag-b",function(){h.b.a.api=f.c||f.z?f.c+"_"+f.z:""});m.d("stag-d",function(){h.b.a.api=
0;f.c=0;f.z=0})},ea:function(){var d=window._hmt;if(d&&d.length)for(var a=0;a<d.length;a++){var b=d[a];switch(b[0]){case "_setAccount":1<b.length&&/^[0-9a-z]{32}$/.test(b[1])&&(f.c|=1,window._bdhm_account=b[1]);break;case "_setAutoPageview":if(1<b.length&&(b=b[1],r===b||p===b))f.c|=2,window._bdhm_autoPageview=b}}},fa:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var d=window._hmt;if(d&&d.length)for(var a=0,b=d.length;a<b;a++)e.e(d[a],
"Array")&&"_trackEvent"!==d[a][0]&&"_trackRTEvent"!==d[a][0]?f.I(d[a]):f.o.push(d[a]);window._hmt=f.Q}},ga:function(){if(0<f.o.length)for(var d=0,a=f.o.length;d<a;d++)f.I(f.o[d]);f.o=q},I:function(d){if(e.e(d,"Array")){var a=d[0];if(f.hasOwnProperty(a)&&e.e(f[a],"Function"))f[a](d)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){f.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.G?(h.b.a.nv=0,h.b.a.st=4):h.b.G=p;var b=h.b.a.u,e=h.b.a.su;h.b.a.u=n.protocol+"//"+document.location.host+
a[1];f.R||(h.b.a.su=document.location.href);h.b.h();h.b.a.u=b;h.b.a.su=e}},_trackEvent:function(a){2<a.length&&(f.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),h.b.h())},_setCustomVar:function(a){if(!(4>a.length)){var e=a[1],g=a[4]||3;if(0<e&&6>e&&0<g&&4>g){f.z++;for(var s=(h.b.a.cv||"*").split("!"),t=s.length;t<e-1;t++)s.push("*");s[e-1]=g+"*"+b(a[2])+"*"+b(a[3]);h.b.a.cv=s.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.va("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],f.R=p)},_trackOrder:function(d){d=d[1];e.e(d,"Object")&&(a(d),f.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=k.stringify(d),h.b.h())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])f.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.h()},_trackRTPageview:function(d){d=
d[1];e.e(d,"Object")&&(a(d),d=k.stringify(d),512>=encodeURIComponent(d).length&&(f.c|=64,h.b.a.rt=d))},_trackRTEvent:function(d){d=d[1];if(e.e(d,"Object")){a(d);d=encodeURIComponent(k.stringify(d));var b=function(a){var d=h.b.a.rt;f.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.h();h.b.a.rt=d},g=d.length;if(900>=g)b.call(this,d);else for(var g=Math.ceil(g/900),s="block|"+Math.round(Math.random()*n.m).toString(16)+"|"+g+"|",t=[],m=0;m<g;m++)t.push(m),t.push(d.substring(900*m,900*m+900)),b.call(this,s+t.join("|")),
t=[]}},_setUserId:function(a){a=a[1];if(e.e(a,"String")||e.e(a,"Number")){var b=h.b.F(),m="hm-"+h.b.a.v;f.T=f.T||Math.round(Math.random()*n.m);g.log("//datax.baidu.com/x.gif?si="+c.id+"&dm="+encodeURIComponent(b)+"&ac="+encodeURIComponent(a)+"&v="+m+"&li="+f.T+"&rnd="+Math.round(Math.random()*n.m))}}};f.init();h.Z=f;return h.Z})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.G=r,this.init())}var b=mt.url,g=mt.L,e=mt.M,k=mt.lang,n=mt.cookie,m=mt.g,f=mt.localStorage,d=mt.sessionStorage,l=h.B,u=h.r;a.prototype={H:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length==a.length},S:function(a,d){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(d)},s:function(a){for(var d=0;d<c.dm.length;d++)if(-1<
c.dm[d].indexOf("/")){if(this.S(a,c.dm[d]))return p}else{var f=b.P(a);if(f&&this.H(f,c.dm[d]))return p}return r},F:function(){for(var a=document.location.hostname,d=0,b=c.dm.length;d<b;d++)if(this.H(a,c.dm[d]))return c.dm[d].replace(/(:\d+)?[\/\?#].*/,"");return a},O:function(){for(var a=0,d=c.dm.length;a<d;a++){var b=c.dm[a];if(-1<b.indexOf("/")&&this.S(document.location.href,b))return b.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},na:function(){if(!document.referrer)return l.i-l.l>c.vdur?1:4;var a=
r;this.s(document.referrer)&&this.s(document.location.href)?a=p:(a=b.P(document.referrer),a=this.H(a||"",document.location.hostname));return a?l.i-l.l>c.vdur?1:4:3},getData:function(a){try{return n.get(a)||d.get(a)||f.get(a)}catch(b){}},setData:function(a,b,e){try{n.set(a,b,{domain:this.F(),path:this.O(),D:e}),e?f.set(a,b,e):d.set(a,b)}catch(g){}},va:function(a){try{n.set(a,"",{domain:this.F(),path:this.O(),D:-1}),d.remove(a),f.remove(a)}catch(b){}},za:function(){var a,d,b,f,e;l.l=this.getData("Hm_lpvt_"+
c.id)||0;13==l.l.length&&(l.l=Math.round(l.l/1E3));d=this.na();a=4!=d?1:0;if(b=this.getData("Hm_lvt_"+c.id)){f=b.split(",");for(e=f.length-1;0<=e;e--)13==f[e].length&&(f[e]=""+Math.round(f[e]/1E3));for(;2592E3<l.i-f[0];)f.shift();e=4>f.length?2:3;for(1===a&&f.push(l.i);4<f.length;)f.shift();b=f.join(",");f=f[f.length-1]}else b=l.i,f="",e=1;this.setData("Hm_lvt_"+c.id,b,c.age);this.setData("Hm_lpvt_"+c.id,l.i);b=l.i==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.s(document.location.href)&&
(""===document.referrer||this.s(document.referrer)))a=0,d=4;this.a.nv=a;this.a.st=d;this.a.cc=b;this.a.lt=f;this.a.lv=e},U:function(){for(var a=[],d=0,b=l.V.length;d<b;d++){var f=l.V[d],e=this.a[f];"undefined"!=typeof e&&""!==e&&a.push(f+"="+encodeURIComponent(e))}d=this.a.et;this.a.rt&&(0===d?a.push("rt="+encodeURIComponent(this.a.rt)):90===d&&a.push("rt="+this.a.rt));return a.join("&")},Aa:function(){this.za();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=m.wa;this.a.cl=m.colorDepth+"-bit";
this.a.ln=m.language;this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=e.oa();this.a.v="1.0.77";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=b.k(a,l.ra)||"";this.a.cp=b.k(a,l.sa)||"";this.a.cw=b.k(a,l.qa)||"";this.a.ci=b.k(a,l.pa)||"";this.a.cf=b.k(a,l.ta)||""},init:function(){try{this.Aa(),0===this.a.nv?this.ya():this.K(".*"),h.b=this,this.$(),
u.q("pv-b"),this.xa()}catch(a){var d=[];d.push("si="+c.id);d.push("n="+encodeURIComponent(a.name));d.push("m="+encodeURIComponent(a.message));d.push("r="+encodeURIComponent(document.referrer));g.log(l.protocol+"//"+l.J+"?"+d.join("&"))}},xa:function(){function a(){u.q("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.G=p,this.a.et=0,this.a.ep="",this.h(a)):a()},h:function(a){var d=this;d.a.rnd=Math.round(Math.random()*l.m);u.q("stag-b");var b=l.protocol+"//"+
l.J+"?"+d.U();u.q("stag-d");d.X(b);g.log(b,function(b){d.K(b);k.e(a,"Function")&&a.call(d)})},$:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),f=-1<document.referrer.indexOf(l.Y)?p:r,e=b.k(a,"jn"),g=/^heatlink$|^select$/.test(e);a&&(d.test(a)&&f&&g)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",l.protocol+"//"+c.js+e+".js?"+this.a.rnd),e=document.getElementsByTagName("script")[0],e.parentNode.insertBefore(a,
e))},X:function(a){var b=d.get("Hm_unsent_"+c.id)||"",f=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+f)+(b?","+b:"");d.set("Hm_unsent_"+c.id,b)},K:function(a){var b=d.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?d.set("Hm_unsent_"+c.id,b):d.remove("Hm_unsent_"+c.id))},ya:function(){var a=this,b=d.get("Hm_unsent_"+
c.id);if(b)for(var b=b.split(","),f=function(d){g.log(l.protocol+"//"+decodeURIComponent(d).replace(/^https?:\/\//,""),function(d){a.K(d)})},e=0,m=b.length;e<m;e++)f(b[e])}};return new a})();
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a={click:function(){for(var a=[],b=[].slice.call(document.getElementsByTagName("a")),b=[].concat.apply(b,document.getElementsByTagName("area")),d=/openZoosUrl\(/,e=0,g=b.length;e<g;e++)d.test(b[e].getAttribute("onclick"))&&a.push(b[e]);return a}},b=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===r)return r},g=function(a,b){return Object.prototype.toString.call(a)==="[object "+b+"]"};window._hmt=window._hmt||[];var e,
k="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),n=function(a,b){if(e===b){window._hmt.push(["_trackPageview",k+a]);for(var d=+new Date;500>=+new Date-d;);return r}if(g(b,"Array")||g(b,"NodeList"))for(var d=0,l=b.length;d<l;d++)if(e===b[d]){window._hmt.push(["_trackPageview",k+a+"/"+(d+1)]);for(d=+new Date;500>=+new Date-d;);return r}};(function(a,b,d){a.addEventListener?a.addEventListener(b,d,p):a.attachEvent&&a.attachEvent("on"+b,d)})(document,"click",function(k){k=k||window.event;e=k.target||k.srcElement;
var f={};for(b(a,function(a,b){f[a]=g(b,"Function")?b():document.getElementById(b)});e&&e!==document&&b(f,n)!==r;)e=e.parentNode})}})();})();
